### ISSUE TITLE
Correct installation procedure?

### ISSUE THREAD

**Issue by tsuchm** [ku-nlp/jumanpp#107]
According to the install instruction described at README.md, I tried the following commands to build and install JUMAN++ on the head of GitHub repository.

```
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX=$HOME/jumanpp ..
$ make
$ make install
```

However, I got the following installation result.  A binary only exists, but neither dictionary nor model exists.

```
$ cd ~/jumanpp
$ ls -R
.:
bin/

./bin:
jumanpp*
```

I think that something necessary instruction is missed in my installation process.
Could you help me?

**Comment by eiennohito** [comment]
I need to be more clear that git version is development and do not contain any model.
It can't be used for analysis (at all).
And models for the previous versions could not be compatible with it because of internal changes.

Please install the package version for the time being:
https://github.com/ku-nlp/jumanpp/releases/download/v2.0.0-rc2/jumanpp-2.0.0-rc2.tar.xz

I need to be more clear about it.

**Comment by tsuchm** [comment]
Got it.
